### ISSUE TITLE
Add themes

### ISSUE THREAD

**Issue by exiler0** [abejfehr/parity#41]
We can make an option available for users which allows them to choose a theme of game. Something like this. 

![image](https://cloud.githubusercontent.com/assets/3627462/17044904/fd81c272-4fe1-11e6-9650-8335487708aa.png)

**Comment by abejfehr** [comment]
Hi @exiler0,

Thanks for extending Parity to allow for themes! I appreciate the work, but I'm actually in the process of rewriting Parity right now into a [Progressive Web App](https://developers.google.com/web/progressive-web-apps/), and because it'll be a rewrite, I'm not going to accept this pull request.

You can always create a fork of parity if you wish!
